[project]
name = "easycrypt"
version = "0.1.0"
authors = [{name = "Daniel Hollarek", email = "daniel.hollarek@googlemail.com"}]
description = "A very good project indeed"
readme = "readme.md"
dependencies = ['cryptography']

[tool.setuptools.packages.find]
include = ["easycrypt*"] # correct
