name: Standard python workflows

on: [push]

jobs:
  ToxTests:
    runs-on: ubuntu-latest
    steps:
      - uses: Somerandomguy10111/actions/toxtests@main
  Dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: Somerandomguy10111/actions/deptry@main
